package uts_toko;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizaalvin
 */
public class frmMain extends javax.swing.JFrame {
        String ID;
        String tgl="";
        String nol_jam="";
        String nol_menit="";
        String nol_detik="";
        String nama_kasir="";
        String banyak_diskon="0%";
        int Jml;
        int sisa;
        int row;
        
    /**
     * Creates new form frmMain
     * @param nama
     */
    public frmMain(String nama) {
        nama_kasir= nama;
        initComponents();
        jNamaKasir.setText(nama);
        setTanggal();
        setJam();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTgl = new javax.swing.JLabel();
        jJam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jHarga = new javax.swing.JTextField();
        jJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jNamaKasir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KASIR TOKO RIZA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 165, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Insyaalah Berkah");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 104, 15);

        jTgl.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jTgl.setText("Tanggal");
        jPanel1.add(jTgl);
        jTgl.setBounds(770, 10, 111, 21);

        jJam.setFont(new java.awt.Font("Arabic Typesetting", 1, 24)); // NOI18N
        jJam.setText("Jam");
        jPanel1.add(jJam);
        jJam.setBounds(770, 30, 150, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 70);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 10, 59, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(170, 10, 59, 15);

        jID.setEditable(false);
        jID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(jID);
        jID.setBounds(20, 30, 120, 30);

        jHarga.setEditable(false);
        jHarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(jHarga);
        jHarga.setBounds(590, 30, 150, 30);

        jJumlah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(jJumlah);
        jJumlah.setBounds(770, 30, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Harga");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(600, 10, 100, 15);

        jNama.setEditable(false);
        jNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(jNama);
        jNama.setBounds(160, 30, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Barang");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(370, 10, 100, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Jumlah");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(780, 10, 59, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buku Tulis", "Kertas Folio", "Pensil", "Bolpoin", "Tipe-X", "Penghapus", "Lakban", "Iqro", "Juz Amma", "Al Quran", "Al Quran Terjemahan", "Buku Sahih Muslim", "Parfum No Alkohol" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(360, 30, 190, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Kasir", "ID Barang", "Barang", "Harga", "Jumlah", "Diskon", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 266, 930, 250);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 1070, 520);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(240, 10, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(340, 10, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(440, 10, 80, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.setMaximumSize(new java.awt.Dimension(80, 20));
        jButton4.setPreferredSize(new java.awt.Dimension(80, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(540, 10, 80, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(640, 10, 80, 30);

        jNamaKasir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNamaKasir.setText("Zz");
        jPanel4.add(jNamaKasir);
        jNamaKasir.setBounds(70, 0, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kasir :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 0, 50, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(-10, 80, 1070, 50);

        setSize(new java.awt.Dimension(936, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        
         ID = jID.getText();
        String Nama = jNama.getText();
        String Barang = (String) jComboBox1.getSelectedItem();
        String Harga = jHarga.getText();
        int Hargaa = Integer.parseInt(Harga);
        String Jumlah = jJumlah.getText();
         Jml = Integer.parseInt(Jumlah);
        String Diskon = banyak_diskon;
        int Totaal = Hargaa * Jml;
        String Total = String.valueOf(Totaal);
        
        
        String SQL = "INSERT INTO tb_transaksi (nama_kasir, barang, harga, jumlah, diskon, total)"
                    + "VALUES('"+Nama+"','"+Barang+"','"+Harga+"','"+Jumlah+"','"+Diskon+"','"+Total+"')";
        int status = koneksiDB.execute(SQL);
            if (status == 1) {
                update();
                bzz();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
                
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            String SQL = "DELETE FROM tb_transaksi";
            int status = koneksiDB.execute(SQL);
            if (status==1) {
                bzz();
            }else{
                
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jID.setText("");
        jHarga.setText("");
        buttonGroup2.clearSelection();
        jJumlah.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bzz();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        diskon();
        struk();
        
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}         ");
        
        try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }   catch (PrinterException ex) {
                System.err.format("Cannot print %s%n", ex.getMessage());
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String Barang = (String) jComboBox1.getSelectedItem();
        String SQL = "SELECT * FROM tb_barang WHERE nama_barang='"+Barang+"';";
        ResultSet rs = koneksiDB.executeQuery(SQL);
            try {
                if (rs.next()) {
                jID.setText(rs.getString(1));
                jNama.setText(nama_kasir);
                jHarga.setText(rs.getString(3));
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jHarga;
    private javax.swing.JTextField jID;
    private javax.swing.JLabel jJam;
    private javax.swing.JTextField jJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNama;
    private javax.swing.JLabel jNamaKasir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTgl;
    // End of variables declaration//GEN-END:variables

    
    public void bzz(){
        
        String kolom[] = {"Nama Kasir","ID Barang","Barang","Harga","Jumlah","Diskon","Total"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        
    String SQL = "SELECT * FROM tb_transaksi";
                    ResultSet rs = koneksiDB.executeQuery(SQL);
                    try {
                        while (rs.next()) {
                            String ID1 = rs.getString(1);
                            String Nama1 = rs.getString(2);
                            String Barang1 = rs.getString(3);
                            String Harga1 = rs.getString(4);
                            String Jumlah1 = rs.getString(5);
                            String Diskon1 = rs.getString(6);
                            String Total1 = rs.getString(7);
                            String data[] = {Nama1,ID1,Barang1,Harga1,Jumlah1,Diskon1,Total1};
                            dtm.addRow(data);
                        }
                    } catch (Exception ex) {
                        Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jTable1.setModel(dtm);
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tgl = kal.format(skrg);
        jTgl.setText(tgl);       
    }
    
    public void setJam(){
        ActionListener taskPerformer;
            taskPerformer = new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    Date dt = new Date();
                    int nilai_jam = dt.getHours();
                    int nilai_menit = dt.getMinutes();
                    int nilai_detik = dt.getSeconds();
                    if (nilai_jam <= 9){
                        nol_jam = "0";
                    }
                    if (nilai_menit <= 9){
                        nol_menit = "0";
                    }
                    if (nilai_detik <= 9){
                        nol_detik = "0";
                    }
                    String jam = nol_jam + Integer.toString(nilai_jam);
                    String menit = nol_menit + Integer.toString(nilai_menit);
                    String detik = nol_detik + Integer.toString(nilai_detik);
                    jJam.setText("Jam "+jam+":"+menit+":"+detik);
                }
            };
            new Timer(100, taskPerformer).start();
    }

    private void update() {
        
        
        String SQL = "SELECT * FROM tb_barang WHERE id_barang='"+ID+"';";
        ResultSet rs = koneksiDB.executeQuery(SQL);
        try {
            if (rs.next()) {
                int stock = Integer.parseInt(rs.getString(4));
                sisa = stock - Jml;
            }
               } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        String SQLI = "UPDATE tb_barang SET stock_barang='"+sisa+"'"
                    + "WHERE id_barang='"+ID+"'";
            int status = koneksiDB.execute(SQLI);
            
    }       

    private void diskon() {
        int total;
        int hzz = 0;
        row = jTable1.getRowCount();
        
        for(int i = 0; i < row ;i++){
            total = Integer.parseInt(jTable1.getValueAt(i, 6).toString());
            hzz += total;
        }
        if(hzz > 100000){

        banyak_diskon="30%";
        }
        else {

        banyak_diskon="0%";
        }
    }

    private void struk() {
        String Nama = jNama.getText();
        int harga = 0;
        int total = 0;
        int harga_diskon;
        for(int i = 0; i < row; i++){
            total = Integer.parseInt(jTable1.getValueAt(i, 6).toString());
            harga += total;
        }
        if(banyak_diskon=="30%"){
            harga_diskon = harga * 70 / 100;
        } else {
            harga_diskon = harga;
        }
        
        String SQL = "INSERT INTO tb_struk (nama_kasir, jumlah_barang, jumlah_harga, diskon, harga_diskon, tanggal)"
                    + "VALUES('"+Nama+"','"+row+"','"+harga+"','"+banyak_diskon+"','"+harga_diskon+"','"+tgl+"')";
        int status = koneksiDB.execute(SQL);
            if (status == 1) {
                update();
                bzz();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
    }
}
